///MAP OF LGA'S AND WARDS
const Map<String, List<String>> lgaMapping = {
  'Agaie': [
    'SELECT WARD',
    'BORO',
    'BOKU',
    'EKOBADEGGI',
    'EKOSSA',
    'EKOWUGI',
    'EKOWUNA',
    'ETSUGAIE',
    'DAUACI',
    'KUTIRIKO',
    'MAGAJI',
    'TAGAGI',
  ],
  'Agwara': [
    'SELECT WARD',
    'ADEHE',
    'AGWATA',
    'BUSURU',
    'GALLAH',
    'KASHINI',
    'KOKOLI',
    'MAGO',
    'PAPIRI',
    'ROFIA',
    'SUTEKU',
  ],
  'Bida': [
    'SELECT WARD',
    'BARIKI',
    'CENIYAN',
    'DOKODZA',
    'KYARI',
    'LANDZU',
    'MASABA I',
    'MASABA II',
    'MASAGA I',
    'MASAGA II',
    'MAYAKI NDAJIYA',
    'NASSARAFU',
    'UMAR/MAJIGI I',
    'UMAR/MAJIGI II',
    'WADATA',
  ],
  'Borgu': [
    'SELECT WARD',
    'BABANNA',
    'KARABONDE',
    'KONKOSO',
    'MALALE',
    'NEW BUSSA',
    'KABE/PISSA',
    'SHAGUNU',
    'WAWA',
    'RIVERINE',
  ],
  'Bosso': [
    'SELECT WARD',
    'BEJI',
    'BOSSO CENTRAL I',
    'BOSSO CENTRAL II',
    'CHANCHAGA',
    'GARATU',
    'KAMPALA',
    'KODO',
    'MAIKUNKELE',
    'MAITUMBI',
    'SHATA',
  ],
  'Chanchaga': [
    'SELECT WARD',
    'LIMAWA A',
    'LIMAWA B',
    'MAKERA',
    'MINNA CENTRAL',
    'MINNA SOUTH',
    'NASARAWA A',
    'NASARAWA B',
    'NASARAWA C',
    'SABON GARI',
    'TUDUN WADA NORTH',
    'TUDUN WADA SOUTH',
  ],
  'Edati': [
    'SELECT WARD',
    'ENAGI',
    'ETSU TASHA',
    'FAZHI',
    'GAZHE I',
    'GAZHE II',
    'GBANGBAN',
    'GONAKI',
    'GUZAN',
    'ROKOTA',
    'SAKPE',
  ],
  'Gbako': [
    'SELECT WARD',
    'BATAGI',
    'BATAKO',
    'EDOKOTA',
    'EDOZHIGI',
    'ETSU AUDU',
    'GBANDAFU',
    'GOGATA',
    'LEMU',
    'NUWANKOTA',
    'SAMMAJIKO',
  ],
  'Gurara': [
    'SELECT WARD',
    'BONU',
    'DIKO',
    'GAWU',
    'IZOM',
    'KABO',
    'KWAKA',
    'LAMBATA',
    'LEFU',
    'SHAKO',
    'TUFA',
  ],
  'Katcha': [
    'SELECT WARD',
    'BAKEKO',
    'BADEGGI',
    'BISANTI',
    'DZWAFU',
    'EDOTZU',
    'ESSA',
    'GBAKOGI',
    'KATCHA',
    'KATAREGI',
    'SIDI SABA',
  ],
  'Kontagora': [
    'SELECT WARD',
    'AREWA',
    'CENTRAL',
    'GABAS',
    'KUDU',
    'MAGAJIYA',
    'MUSUGA',
    'MADARA',
    'NAGWAMATSE',
    'RAFIN GORA',
    'TUNGA NAWA',
    'TUNGA KAWO',
    'USALLE',
    'YAMMA',
  ],
  'Lapai': [
    'SELECT WARD',
    'AREWA/YAMMA',
    'BIRNIN MAZA',
    'EBBO/GBACINKU',
    'EVUTI KPADA',
    'GULU ANGUWA',
    'GUWA ABUGI',
    'KURDI/ZAGO',
    'KUDU/GABAS',
    'MUYE/EGBA',
    'TAKUTI SHAKU',
  ],
  'Lavun': [
    'SELECT WARD',
    'BUSU/KUCHI',
    'BATATI',
    'DASSUN',
    'DOKO',
    'DABBAN',
    'GBAKO',
    'GABA',
    'JIMA',
    'KUTIGI',
    'KUSOTACHI',
    'LAGUN',
    'MAMBE',
  ],
  'Magama': [
    'SELECT WARD',
    'AUNA CENTRAL',
    'AUNA EAST CENTRAL',
    'AUNA EAST',
    'AUNA SOUTH EAST',
    'AUNA SOUTH',
    'IBELU CENTRAL',
    'IBELU EAST',
    'IBELU NORTH',
    'IBELU WEST',
    'NASKO',
    'NASARAWA',
  ],
  'Mariga': [
    'SELECT WARD',
    'BERI',
    'BOBI',
    'GULBI KOKA',
    'GALMA',
    'INKWAI',
    'IGWAMA',
    'KAKIHUM',
    'KONTOKORO',
    'KUMBASHI',
    'MABURYA',
  ],
  'Mashegu': [
    'SELECT WARD',
    'BABBAN RAMI',
    'DAPANGI/MAKERA',
    'IBBI',
    'KABOJI',
    'KASANGA',
    'KWATACHI',
    'KULHO',
    'MASHEGU',
    'MAZAKUKA',
    'SAHO RAMI',
  ],
  'Mokwa': [
    'SELECT WARD',
    'BOKANI',
    'GBAJIBO/MUWO',
    'GBARA',
    'JAAGI',
    'JEBA NORTH',
    'KPAKI',
    'KUDU',
    'LABOZHI',
    'MOKWA',
    'MUREGI',
    'RABBAN/DAYAHKO',
  ],
  'Munya': [
    'SELECT WARD',
    'BENI',
    'DANDAUDU',
    'DANGUNU',
    'DAZA',
    'FUKA',
    'GINI',
    'GUNI',
    'KABULA',
    'KAZAI',
    'KUCHI',
    'SARKI PAWA',
  ],
  'Paikoro': [
    'SELECT WARD',
    'ADUNI',
    'CHIMBI',
    'GWAM',
    'ISHAU',
    'JERE',
    'KAFIN KORO',
    'KWAGANA',
    'KWAKUTI',
    'NIKUCHI T',
    'PAIKORO CENTRA',
    'TUTUNGO JEDNA',
  ],
  'Rafi': [
    'SELECT WARD',
    'KAGARA GARI',
    'KAKURI',
    'KONGOMA CENTRA',
    'KONGOMA EAST',
    'KONGOMA NORTH',
    'KONGOMA SOUTH',
    'KUNDUN',
    'SABON GARI',
    'TEGINA GARI',
    'TEGINA WEST',
    'YAKILA',
  ],
  'Rijau': [
    'SELECT WARD',
    'DANRANGI',
    'DUGGE',
    'DUKKU',
    'GENU',
    "JAMA'ARE",
    'RIJAU',
    'SHAMBO',
    'T/BUNU',
    'T/MAGAJIYA',
    'UCHE',
    'WARARI',
  ],
  'Shiroro': [
    'SELECT WARD',
    'ALLAWA',
    'BANGAJIYA',
    'BASSA/KUKOKI',
    'EGWA/ GWADA',
    'ERANA',
    'GALKOGO',
    'GURMANA',
    'GUSSORO',
    'KATO',
    'KUSHAKA',
    'KWAKI',
    'MANTA',
    'PINA',
    'SHE',
    'UBANDOMA',
  ],
  'Suleja': [
    'SELECT WARD',
    'BAGMAMA A',
    'BAGMAMA B',
    'HASHIMI A',
    'HASHIMI B',
    'IKU SOUTH I',
    'IKU SOUTH II',
    'KURMIN SARKI',
    'MAGAJIYA',
    'MAJE NORTH',
    'WAMBAI',
  ],
  'Tafa': [
    'SELECT WARD',
    'DOGON',
    'GARAM',
    'IJA GWARI',
    'IJA KORO',
    'IKU',
    'NEW BWARI',
    'WUSE WEST',
    'WUSE EAST',
    'ZUMA EAST',
    'ZUMA WEST',
  ],
  'Wushishi': [
    'SELECT WARD',
    'AKARE',
    'BARWA',
    'GWARJIKO',
    'KANWARI',
    'KODO',
    'KWATA',
    'LOKOGOMA',
    'MAITO',
    'SABON GARI',
    'TUKUNJI YAMIGI',
    'ZUNGERU',
  ],
};
